version: "3.5"
services:
  nifi:
    image: profirator/nifi:1.9.2
    ports:
        - 8080:8080
        - 8082:8082
    volumes:
        - ./nifi/logs:/opt/nifi/logs
        - ./nifi/flowfile_repository:/opt/nifi/flowfile_repository
        - ./nifi/database_repository:/opt/nifi/database_repository
        - ./nifi/content_repository:/opt/nifi/content_repository
        - ./nifi/provenance_repository:/opt/nifi/provenance_repository
